In [13]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

arr2d = np.array([[1, 3], [100, 101], ["John", "Peter"], [True, 20]])
print(arr2d)
print(arr2d.shape)

print(arr + 1) #[2 3 4]
print(arr ** 2) #[1 4 9]
print(arr * 3) #[3 6 9]


# list
list = [1, 2, 3]
print(list * 2) #[1, 2, 3, 1, 2, 3]

[1 2 3]
<class 'numpy.ndarray'>
[['1' '3']
 ['100' '101']
 ['John' 'Peter']
 ['True' '20']]
(4, 2)
[2 3 4]
[1 4 9]
[3 6 9]
[1, 2, 3, 1, 2, 3]


In [15]:
arr2 = np.array([100, 20, 80, 6])
print(np.mean(arr2)) # 51.5
print(np.median(arr2))
print(np.min(arr2))
print(np.max(arr2))
print(np.std(arr2))

arr2_reshaped = arr2.reshape(2, 2)
print(arr2_reshaped)

51.5
50.0
6
100
39.455671328720285
[[100  20]
 [ 80   6]]
